version: "3.8"
services:
  app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
